#!/usr/bin/env python

from livereload import Server, shell

server = Server()
server.watch("README.md", shell("make"))
server.watch("img/*", shell("make"))
server.watch("lec/*.md", shell("make"))
server.watch("ws/*.ipynb", shell("make"))
server.serve(root="_build/html")
