#!/usr/bin/env python

from livereload import Server, shell

server = Server()
server.watch("README.md", shell("make build slides"))
server.watch("img/*", shell("make build slides"))
server.watch("lec/*.md", shell("make build slides"))
server.watch("ws/*.ipynb", shell("make build slides"))
server.serve(root="_build/")
