#!/usr/bin/env python

from livereload import Server, shell

server = Server()
server.watch("README.md", shell("make build "))
server.watch("img/*", shell("make build "))
server.watch("lec/*.md", shell("make build "))
server.watch("ws/*.md", shell("make build "))
server.watch("ws/*.ipynb", shell("make build "))

port = 5500
unserved = True
while unserved:
    try:
        server.serve(root="_build/", port=port)
        unserved = False
    except OSError as e:
        print(e)
        port = port + 1
        continue
